config/routes.rb
Osem::Application.routes.draw do

  if CONFIG['authentication']['ichain']['enabled']
    devise_for :users, controllers: { registrations: :registrations }
  else
    devise_for :users,
               controllers: {
                   registrations: :registrations, confirmations: :confirmations,
                   omniauth_callbacks: 'users/omniauth_callbacks' },
               path: 'accounts'
  end

  # Use letter_opener_web to open mails in browser (e.g. necessary for Vagrant)
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :users, except: [:new, :index, :create, :destroy]

  namespace :admin do
    resources :users
    resources :people
    resources :comments, only: [:index]
    resources :conference do
      resource :contact, except: [:index, :new, :create, :show, :destroy]
      resources :photos, except: [:show]
      resource :schedule, only: [:show, :update]
      get 'commercials/render_commercial' => 'commercials#render_commercial'
      resources :commercials, only: [:index, :create, :update, :destroy]
      get '/dietary_choices' => 'dietchoices#show', as: 'dietary_list'
      patch '/dietary_choices' => 'dietchoices#update', as: 'dietary_update'
      get '/volunteers_list' => 'volunteers#show'
      get '/volunteers' => 'volunteers#index', as: 'volunteers_info'
      patch '/volunteers' => 'volunteers#update', as: 'volunteers_update'

      resources :registrations, except: [:create, :new] do
        member do
          patch :toggle_attendance

        end
      end

      # Singletons
      resource :splashpage
      resource :venue do
        resources :rooms, except: [:show]
      end
      resource :registration_period
      resource :program do
        resource :cfp
        resources :tracks
        resources :event_types
        resources :difficulty_levels
        resources :events do
          member do
            post :comment
            patch :accept
            patch :confirm
            patch :cancel
            patch :reject
            patch :unconfirm
            patch :restart
            get :vote
          end
          resource :speaker, only: [:edit, :update]
        end
      end

      resources :tickets
      resources :sponsors, except: [:show]
      resources :lodgings, except: [:show]
      resources :targets, except: [:show]
      resources :campaigns, except: [:show]
      resources :emails, only: [:show, :update, :index]
      resources :roles, except: [ :new, :create ] do
        member do
          post :toggle_user
        end
      end

      resources :sponsorship_levels, except: [:show] do
        member do
          patch :up
          patch :down
        end
      end

      resources :questions do
        collection do
          patch :update_conference
        end
      end
    end
  end

  resources :conference, only: [:index, :show] do
    resource :program, except: :destroy do
      resources :proposal, except: :destroy do
        get 'commercials/render_commercial' => 'commercials#render_commercial'
        resources :commercials, only: [:create, :update, :destroy]
        member do
          patch '/withdraw' => 'proposal#withdraw'
          patch '/confirm' => 'proposal#confirm'
          patch '/restart' => 'proposal#restart'
          get '/vote' => 'proposal#vote'
        end
      end
    end

    # TODO: change conference_registrations to singular resource
    resource :conference_registrations, path: 'register' do
      collection do
        get :confirmcheck
        patch :confirmupdate
      end
    end
    resources :tickets, only: [:index]
    resources :ticket_purchases, only: [:create, :destroy]
    resource :subscriptions, only: [:create, :destroy]

    member do
      get :schedule
      get :new_proposals
      get :completeschedule
      get :subnationalschedule
      get :eventlists
      get :attendeelist
    end

  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :conferences, only: [ :index, :show ] do
        resources :rooms, only: :index
        resources :tracks, only: :index
        resources :speakers, only: :index
        resources :events, only: :index
      end
      resources :rooms, only: :index
      resources :tracks, only: :index
      resources :speakers, only: :index
      resources :events, only: :index
    end
  end

  get '/admin' => redirect('/admin/conference')

  root to: 'conference#index', via: [:get, :options]
end

app/models/ahoy/event.rb
module Ahoy
  class Event < ActiveRecord::Base
    self.table_name = 'ahoy_events'

    belongs_to :visit
    belongs_to :user

    serialize :properties, JSON
  end
end

app/models/event_type.rb
class EventType < ActiveRecord::Base
  belongs_to :program
  has_many :events, dependent: :restrict_with_error

  validates :title, presence: true
  validates :length, numericality: {greater_than: 0}
  validates :minimum_abstract_length, presence: true
  validates :maximum_abstract_length, presence: true
  validates :minimum_objective_length, presence: true
  validates :maximum_objective_length, presence: true

  alias_attribute :name, :title
end

app/controllers/admin/events_controller.rb
module Admin
  class EventsController < Admin::BaseController
    load_and_authorize_resource :conference, find_by: :short_title
    load_and_authorize_resource :program, through: :conference, singleton: true
    load_and_authorize_resource :event, through: :program

    before_action :get_event, except: [:index, :new, :create]

    # FIXME: The timezome should only be applied on output, otherwise
    # you get lost in timezone conversions...
    # around_filter :set_timezone_for_this_request

    def set_timezone_for_this_request(&block)
      Time.use_zone(@conference.timezone, &block)
    end

    def index
      @events = @program.events.order("updated_at DESC")
      @tracks = @program.tracks
      @difficulty_levels = @program.difficulty_levels
      @machine_states = @events.state_machine.states.map
      @event_types = @program.event_types
      @event_type_titles = Hash.new('?')
      @event_types.each do |event_type|
        @event_type_titles[event_type.id] = event_type.title
      end
      @track_titles = Hash.new('?')
      @tracks.each do |track|
        @track_titles[track.id] = track.name;
      end
      
      @mystates = []
      @mytypes = []
      @eventstats = {}
      @totallength = 0

      @machine_states.each do |mystate|
        length = 0
        events_mystate = @events.where('state' => mystate.name)
        if events_mystate.count > 0
          @mystates << mystate
          events_mystate.each do |myevent|
            length += myevent.event_type.length
          end
          @eventstats["#{mystate.name}"] = { 'count' => events_mystate.count, 'length' => length }
        end
      end

      @event_types.each do |mytype|
        events_mytype = @events.where('event_type_id' => mytype.id)
        if events_mytype.count > 0
          @mytypes << mytype
        end
      end
      @mytypes.each do |mytype|
        @mystates.each do |mystate|
          events_mytype = @events.where('event_type_id' => mytype.id)
          events_mytype_mystate = events_mytype.where('state' => mystate.name)
          typelength = 0
          if events_mytype_mystate.count > 0
            events_mytype_mystate.each do |myevent|
              typelength += myevent.event_type.length
              @totallength += myevent.event_type.length
            end

            if @eventstats[mytype.title].nil?
              @eventstats[mytype.title] = { 'count' => events_mytype.count,
                                            'length' => events_mytype.count * mytype.length }
            end

            tmp = { "#{mystate.name}" => { 'type_state_count' => events_mytype_mystate.count,
                                           'type_state_length' => typelength } }
            @eventstats[mytype.title].merge!(tmp)
          end
        end
      end
      @eventstats['totallength'] = @totallength

      respond_to do |format|
        format.html
        # Explicity call #to_json to avoid the use of EventSerializer
        format.json { render json: Event.where(state: :confirmed, program: @program).to_json }
      end
    end
    
    def new
      @event = @program.events.new
      @tracks = @program.tracks
      @event_types = @program.event_types
      #@url = admin_conference_program_events_path(@conference.short_title)
    end

    def show
      @tracks = @program.tracks
      @event_types = @program.event_types
      @comments = @event.root_comments
      @comment_count = @event.comment_threads.count
      @ratings = @event.votes.includes(:user)
      @difficulty_levels = @program.difficulty_levels
    end

    def edit
      @event_types = @program.event_types
      @tracks = Track.all
      @comments = @event.root_comments
      @comment_count = @event.comment_threads.count
      @user = @event.submitter
      @url = admin_conference_program_event_path(@conference.short_title, @event)
    end

    def comment
      comment = Comment.new(comment_params)
      comment.commentable = @event
      comment.user_id = current_user.id
      comment.save!
      if !params[:parent].nil?
        comment.move_to_child_of(params[:parent])
      end

      redirect_to admin_conference_program_event_path(@conference.short_title, @event)
    end
    
    def create
      submitters_add = params[:event].delete :submitters_add
      speakers_add = params[:event].delete :speakers_add
      @event = Event.new(event_params)
      @event.program = @program
      authorize! :new, @event
      if @event.save
        redirect_to admin_conference_program_event_path(@conference.short_title, @event)
      else
        render "new"
      end
    end

    def update
      existing_submitters = Hash.new(false)
      submitters_checkboxes = event_params.delete :submitters_checkboxes
      submitters_checkboxes.each do |value|
        if value.length > 0
          user = User.find_by_id(value)
          if !user.nil?
            existing_submitters[user.id] = true
          end
        end
      end
      @event.submitters.each do |event_user|
        if !existing_submitters.has_key?(event_user.user_id)
          @event.event_users.destroy(event_user)
        end
      end
      submitters_add = event_params.delete :submitters_add
      submitters_add.split(',').each do |value|
        value = value.strip.to_i
        if value != 0
          user = User.find_by_id(value)
          if !user.nil?
            @event.event_users.new(user: user, event_role: 'submitter')
          end
        end
      end
      existing_speakers = Hash.new(false)
      speakers_checkboxes = event_params.delete :speakers_checkboxes
      speakers_checkboxes.each do |value|
        if value.length > 0
          user = User.find_by_id(value)
          if !user.nil?
            existing_speakers[user.id] = true
          end
        end
      end
      @event.speakers.each do |event_user|
        if !existing_speakers.has_key?(event_user.user_id)
          @event.event_users.destroy(event_user)
        end
      end
      speakers_add = event_params.delete :speakers_add
      speakers_add.split(',').each do |value|
        value = value.strip.to_i
        if value != 0
          user = User.find_by_id(value)
          if !user.nil?
            @event.event_users.new(user: user, event_role: 'speaker')
          end
        end
      end
      @event.save
      if @event.update_attributes(event_params)

        if request.xhr?
          render js: 'index'
        else
          flash[:notice] = "Successfully updated event with ID #{@event.id}."
          redirect_back_or_to(admin_conference_program_event_path(@conference.short_title, @event))
        end
      else
        @url = admin_conference_program_event_path(@conference.short_title, @event)
        flash[:notice] = 'Update not successful. ' + @event.errors.full_messages.to_sentence
        render :edit
      end
    end

    def accept
      send_mail = @event.program.conference.email_settings.send_on_accepted
      subject = @event.program.conference.email_settings.accepted_subject.blank?
      update_state(:accept, 'Event accepted!', true, subject, send_mail)
    end

    def confirm
      update_state(:confirm, 'Event confirmed!')
    end

    def cancel
      update_state(:cancel, 'Event canceled!')
    end

    def reject
      send_mail = @event.program.conference.email_settings.send_on_rejected
      subject = @event.program.conference.email_settings.rejected_subject.blank?
      update_state(:reject, 'Event rejected!', true, subject, send_mail)
    end

    def restart
      update_state(:restart, 'Review started!')
    end

    def vote
      @ratings = @event.votes.includes(:user)

      if (votes = current_user.votes.find_by_event_id(params[:id]))
        votes.update_attributes(rating: params[:rating])
      else
        @myvote = @event.votes.build
        @myvote.user = current_user
        @myvote.rating = params[:rating]
        @myvote.save
      end

      respond_to do |format|
        format.html { redirect_to admin_conference_program_event_path(@conference.short_title, @event) }
        format.js
      end
    end

    private

    def event_params
      params.require(:event).permit!
    end

    def comment_params
      params.require(:comment).permit(:commentable, :body, :user_id)
    end

    def get_event
      @event = @conference.program.events.find(params[:id])
      if !@event
        redirect_to admin_conference_program_events_path(conference_id: @conference.short_title),
                    error: 'Error! Could not find event!'
        return
      end
      @event
    end

    def update_state(transition, notice, mail = false, subject = false, send_mail = false)
      alert = @event.update_state(transition, mail, subject, send_mail, params[:send_mail].blank?)
      if alert.blank?

        flash[:notice] = notice
        redirect_back_or_to(admin_conference_program_events_path(conference_id: @conference.short_title)) && return
      else
        flash[:error] = alert
        return redirect_back_or_to(admin_conference_program_events_path(conference_id: @conference.short_title)) && return
      end
    end
  end
end

app/controllers/api/v1/events_controller.rb
module Api
  module V1
    class EventsController < Api::BaseController
      load_resource :conference, find_by: :short_title
      respond_to :json

      def index
        events = Event.includes(:track, :room, :event_type, event_users: :user)

        if @conference
          events = events.where(program: @conference.program)
        end

        respond_with events.confirmed
      end
    end
  end
end

app/views/admin/events/_change_state_dropdown.html.haml
- if event.transition_possible? :accept
  %li= link_to 'Accept event',
  accept_admin_conference_program_event_path(@conference.short_title, event),
  method: :patch, id: "accept_event_#{event.id}"

  - if @conference.email_settings.send_on_accepted?
    %li= link_to 'Accept event (without email)',
    accept_admin_conference_program_event_path(@conference.short_title, event, send_mail: false),
    method: :patch, hint: 'Accept this event without sending an automated email.',
    id: "accept_event_without_mail_#{event.id}"

- if event.transition_possible? :reject
  %li= link_to 'Reject event',
  reject_admin_conference_program_event_path(@conference.short_title, event),
  method: :patch, confirm: 'Are you sure?', id: "reject_event_#{event.id}"

  - if @conference.email_settings.send_on_rejected?
    %li= link_to 'Reject event (without email)',
    reject_admin_conference_program_event_path(@conference.short_title, event, send_mail: false),
    method: :patch, confirm: 'Are you sure?', id: "reject_event_without_mail_#{event.id}"

- if event.transition_possible? :restart
  %li= link_to 'Start review',
  restart_admin_conference_program_event_path(@conference.short_title, event),
  method: :patch, id: "restart_event_#{event.id}"

- if event.transition_possible? :confirm
  %li= link_to 'Confirm event',
  confirm_admin_conference_program_event_path(@conference.short_title, event),
  method: :patch, id: "confirm_event_#{event.id}",
  hint: 'Confirm that the speaker(s) will be present and that the event will actually take place.'

- if event.transition_possible? :cancel
  %li= link_to 'Cancel event',
  cancel_admin_conference_program_event_path(@conference.short_title, event),
  method: :patch, id: "cancel_event_#{event.id}",
  hint: 'Mark this event as cancelled. Usually this means that the speakers had to cancel their appearance.'

app/views/admin/events/_nested_comments.html.haml
%div{style: "padding-left:#{padding}px"}
  .well.comment-section
    %strong= comment.user.name
    %i= comment.created_at
    %p.comment-body= comment.body
    %div
      %a.pull-right.comment-reply-link{href: "#"} Reply
      .comment-reply
        = semantic_form_for :comment, url:  "#{comment_admin_conference_program_event_path(@conference.short_title, comment.commentable_id)}", method: :post do |f|
          = f.input :body
          %input{name: "parent", type: "hidden", value: "#{comment.id}"}
          %input{name: "authenticity_token", type: "hidden", value: "#{form_authenticity_token}"}
          %button.btn.btn-primary.pull-right{name: "button", type: "submit"} Add Reply
  - comment.children.each do |child|
    = render "nested_comments", comment: child, padding: 50

app/views/admin/events/_proposal.html.haml
.row
  .col-md-12
    %h3
      = @event.title
      %br
      %small
        = @event.subtitle
      = link_to 'Edit', edit_admin_conference_program_event_path(@conference.short_title, @event), class: 'btn btn-mini btn-primary pull-right'

.row
  .col-md-12
    %table.table
      %tr
        %td.col-md-2
          %b Type
        %td
          .dropdown
            = link_to '#', class: 'dropdown-toggle', id: 'type-dropdown' do
              - if @event.event_type.nil?
                Event Type
              - else
                = @event.event_type.title
              <b class='caret'></b>
            %ul.dropdown-menu
              - @event_types.each do |type|
                %li= link_to type.title,
                admin_conference_program_event_path(@conference.short_title,
                                            @event,
                                            event: { event_type_id: type.id }),
                method: :patch
      %tr
        %td
          %b Highlight
        %td
          = check_box_tag @conference.short_title, @event.id, @event.is_highlight,
            method: :patch, url: "/admin/conference/#{@conference.short_title}/program/events/#{@event.id}?event[is_highlight]=",
            class: 'switch-checkbox', data: { size: 'small',
                                              off_color: 'warning',
                                              on_text: 'Yes',
                                              off_text: 'No' }

      %tr
        %td
          %b State
        %td
          .dropdown
            = link_to '#', class: 'dropdown-toggle' do
              = @event.state.humanize
              <b class='caret'></b>
            %ul.dropdown-menu
              = render 'change_state_dropdown', event: @event
      %tr
        %td
          %b Track
        %td
          .dropdown
            = link_to '#', class: 'dropdown-toggle', id: 'track-dropdown' do
              - if @event.track.nil?
                Track
              - else
                = @event.track.name
              <b class="caret"></b>
            %ul.dropdown-menu
              - @tracks.each do |track|
                %li= link_to track.name,
                admin_conference_program_event_path(@conference.short_title,
                                            @event,
                                            event: { track_id: track.id }),
                method: :patch
      - if !@event.room.nil?
        %tr
          %td
            %b Room
          %td
            = @event.room.name
      - if !@event.start_time.nil?
        %tr
          %td
            %b Scheduled time
          %td
            = @event.start_time
      %tr
        %td
          %b Submitter
        %td
          - @event.submitters.each do |submitter|
            - submitter_user = submitter.user
            = link_to submitter_user.name, edit_admin_user_path(submitter_user), target: '_blank'
            - if submitter_user.registrations.count < 1
              %span{:style=>"color: #F7819F"}
                (Unregistered!)
            %br
      %tr
        %td
          %b Contact phone number
        %td
          = @event.contact_phone_number
      %tr
        %td
          %b Submitted on
        %td= @event.created_at
      %tr
        %td
          %b Last updated on
        %td= @event.updated_at
      %tr
        %td
          %b Objective
        %td= markdown(@event.objective)
      %tr
        %td
          %b Abstract
        %td= markdown(@event.abstract)
      %tr
        %td
          %b Speakers
        %td= @event.proposal_additional_speakers
      %tr
        %td
          %b Description
        %td= simple_format(@event.description)
      %tr
        %td
          %b Attachments
        %td
          -if @event.resource1?
            = link_to @event.resource1.original_filename, @event.resource1.url
            = @event.resource1.size
            1
            = number_to_human_size(@event.resource1.size)
            %br
          -if @event.resource2?
            = link_to @event.resource2.original_filename, @event.resource2.url
            = @event.resource2.size
            2
            = number_to_human_size(@event.resource2.size)
            %br
          -if @event.resource3?
            = link_to @event.resource3.original_filename, @event.resource3.url
            = @event.resource3.size
            3
            = number_to_human_size(@event.resource3.file_size)
            %br
      %tr
        %td
          %b Language
        %td
          .dropdown
            = link_to '#', class: 'dropdown-toggle', id: 'language-dropdown' do
              - if @event.language.nil?
                Language
              - else
                = @event.language
              <b class="caret"></b>
            %ul.dropdown-menu
              - ['fr', 'en'].each do |language|
                %li= link_to language,
                admin_conference_program_event_path(@conference.short_title,
                                            @event,
                                            event: { language: language }),
                method: :patch
      %tr
        %td
          %b Expected audience
        %td= @event.expected_audience

.row
  = link_to "Comments (#{@comment_count})", '#', id: 'event-comment-link'
  #comments-div
    %hr
    %ul.media
      %div
        .row-fluid
          = semantic_form_for :comment, url: comment_admin_conference_program_event_path(@conference.short_title, @event.id), method: :post do |f|
            = f.input :body
            = f.submit 'Add Comment', class: 'btn btn-primary pull-right'
        %br
        %br
        - @comments.each do |comment|
          %div
            = render partial: 'nested_comments', locals: { comment: comment, padding: 0}

app/views/admin/events/_user_fields.html.haml
.nested-fields
  = f.inputs do
    = f.input :email
    = f.input :name
  = remove_association_link :user, f

app/views/admin/events/_voting.html.haml
%table.table#myrating
  %tr
    %td.col-md-2
      %b Rating
    %td
      - if @event.average_rating.to_f > 0
        #{@event.average_rating}/#{@conference.program.rating}
      - else
        Rating: 0/#{@conference.program.rating}

      - @conference.program.rating.times do |counter|
        - if @event.average_rating.to_f.round == counter+1
          = label_tag "label_rating", "", :class => "avgrating", :avgrate => true
          = javascript_tag "$('label[avgrate=true]').prevAll().andSelf().addClass('bright');"
        - else
          = label_tag "label_rating", "", :class => "avgrating"
  %tr
    %td
      %b Voters
    %td
      = @event.voters.length
      - if @event.voters.length > 0
        (
        = @ratings.map {|x| "#{x.name}"}.join ', '
        )
  %tr
    %td
      %b Your vote
    %td
      - @conference.program.rating.times do |counter|
        - voted = @event.voted?(@event, current_user)
        - if voted && voted.rating == counter+1
          = link_to "", vote_admin_conference_program_event_path(@conference.short_title, @event, :rating => counter+1), :remote => true, :id =>"label#{counter+1}", :class => "myrating", :voted => true
        - else
          = link_to "", vote_admin_conference_program_event_path(@conference.short_title, @event, :rating => counter+1), :remote => true, :id =>"label#{counter+1}", :class => "myrating"
      %br

  - if @ratings.length > 0
    - @ratings.each do |rate|
      - unless rate.user_id == current_user.id
        %tr
          %td
            = rate.name
          %td
            - @conference.program.rating.times do |counter|
              - voted = @event.voted?(@event, rate.user)
              - if voted && voted.rating == counter+1
                = label_tag "label#{counter+1}", "", :class => "othersrating", :voted => true
                = javascript_tag "$('label[voted=true]').prevAll().andSelf().addClass('bright');"
              - else
                = label_tag "label#{counter+1}", "", :class => "othersrating"
:javascript
  $(function () {
    var checkedId = $("a[voted='true']").attr('id');
    $('a[id=' + checkedId + ']').prevAll().andSelf().addClass('bright');
  });

  $(".myrating").hover(
    function() {    // mouseover
        $(this).prevAll().andSelf().addClass('glow');
    },
    function() {  // mouseout
        $(this).siblings().andSelf().removeClass('glow');
    }
  );

  $(".myrating").click(function() {
    $(this).siblings().removeClass("bright");
    $(this).prevAll().andSelf().addClass("bright");
  });

app/views/admin/events/index.html.haml
- Time::DATE_FORMATS[:updated_at] = '%d/%m %H:%m'
- Time::DATE_FORMATS[:litteral] = '%d/%m à %H:%m'
- last_signin = current_user.last_sign_in_at
.row
  .col-md-12
    .page-header
      %h1
        Events
        - if @events.any?
          = "(#{@events.length})"
      %p
        En rouge, les évènements mis à jour depuis votre dernière connexion le
        = last_signin.to_s(:litteral)
      %p
        = link_to "New event", new_admin_conference_program_event_path(@conference.short_title), target: '_blank'
.row
  .col-md-12
    %table.table.table-striped.table-bordered.table-hover
      %thead
        %th
          %b ID
        %th
          %b Mise à jour
        %th
          %b State
        %th
          %b Title
        %th
          %b Submitter
        %th
          %b Speaker
        %th
          %b Pre-registration
        %th
          %b Type
        %th
          %b Track
        %th
          %b Language
      %tbody.notranslate
      - @events.each do |event|
        - if event.updated_at > last_signin
          - updatecolor="#ff0000"
        - else
          - updatecolor="inherited"
        %tr
          %td
            = event.id
          %td{:style=>"color: #{updatecolor}"}
            = event.updated_at.to_s(:updated_at)
          - if event.state == "confirmed"
            - color="#00ff00"
          - elsif event.state === "new"
            - color="#ff9900"
          %td{:style=>"color: #{color}"}
            = event.state
          %td
            = link_to event.title, edit_admin_conference_program_event_path(@conference.short_title, event), target: '_blank'
          %td
            - event.submitters.each do |submitter|
              - submitter_user = submitter.user
              = link_to submitter_user.name, edit_admin_user_path(submitter_user), target: '_blank'
              - if submitter_user.registrations.count < 1
                %span{:style=>"color: #F7819F"}
                  (Unregistered!)
              %br
          %td
            = event.speaker_names
          %td
            = event.require_registration
          %td
            - if event.event_type_id.nil?
              Event Type
            - else
              = @event_type_titles[event.event_type_id]
          %td
            - if event.track_id.nil?
              Track
            - else
              = @track_titles[event.track_id]
          %td
            - if event.language.nil?
              Language
            - else
              = event.language

app/views/admin/events/new.html.haml
= semantic_form_for(@event, url: admin_conference_program_events_path) do |f|
  = f.inputs name: 'Event' do
    = f.input :state, as: :select, collection: [:new, :withdrawn, :canceled, :rejected, :unconfirm, :confirmed]
  
    = f.input :title, as: :string, required: true

    = f.input :subtitle, as: :string

    - if @program.tracks.any?
      = f.input :track_id, as: :select,
                collection: @program.tracks.map {|track| ["#{track.name}", track.id] },
                include_blank: true

    = f.input :event_type_id, as: :select,
      collection: @conference.program.event_types.map {|type| ["#{type.title} - #{show_time(type.length)}", type.id,
      data: { abstract_min_words: type.minimum_abstract_length, abstract_max_words: type.maximum_abstract_length,
        objective_min_words: type.minimum_objective_length, objective_max_words: type.maximum_objective_length }]},
      include_blank: false, label: 'Type', input_html: { class: 'select-help-toggle' }

    = f.input :require_registration, label: 'Require participants to register'
      
    - @conference.program.event_types.each do |event_type|
      %span{ class: 'help-block select-help-text event_event_type_id collapse', id: "#{event_type.id}-help" }
        = event_type.description

    :javascript
      $("##{@conference.program.event_types.first.id}-help").collapse('show');


    ~ f.input :objective, hint: markdown_hint(), input_html: { rows: 5 , required: true , data: { provide: 'markdown-editable' }, class: 'notranslate'},
    required: true, class: 'notranslate'

    %p
      You have used
      %span#objective-count.notranslate #{@event.objective_word_count}
      words. Objective of the presentation must be between
      %span#objective-minimum-word-count.notranslate
        0
      and
      %span#objective-maximum-word-count.notranslate
        250
      words.

    ~ f.input :abstract, input_html: { required: true, rows: 5, data: { provide: 'markdown-editable' }, class: 'notranslate'},
      required: true, hint: link_to('Tips to improve your presentations', 'http://blog.hubspot.com/blog/tabid/6307/bid/5975/10-Rules-to-Instantly-Improve-Your-Presentations.aspx')

    %p
      You have used
      %span#abstract-count.notranslate #{@event.abstract_word_count}
      words.

    = f.input :proposal_additional_speakers, as: :string, label: 'Speakers', input_html: {class: 'notranslate'}
    
    = f.input :language, as: :select, collection: [['Chose a language', ''], ['French', 'fr'], ['English', 'en']]

    = f.input :expected_audience, as: :number

    = f.input :description, input_html: { rows: 5 }, label: 'Requirements'
     
    = f.input :contact_phone_number, as: :string, required: true, input_html: { required: true }
    %span{ class: 'help-block' }
      In international format, with the country code, for example "+14155552671".

  %p.text-right
    = f.submit 'Create Event', class: 'btn btn-success'

app/views/admin/events/vote.js.erb
$('table#myrating').replaceWith("<%= escape_javascript(render :partial => 'voting') %>");