config/routes.rb
Osem::Application.routes.draw do

  if CONFIG['authentication']['ichain']['enabled']
    devise_for :users, controllers: { registrations: :registrations }
  else
    devise_for :users,
               controllers: {
                   registrations: :registrations, confirmations: :confirmations,
                   omniauth_callbacks: 'users/omniauth_callbacks' },
               path: 'accounts'
  end

  # Use letter_opener_web to open mails in browser (e.g. necessary for Vagrant)
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :users, except: [:new, :index, :create, :destroy]

  namespace :admin do
    resources :users
    resources :people
    resources :comments, only: [:index]
    resources :conference do
      resource :contact, except: [:index, :new, :create, :show, :destroy]
      resources :photos, except: [:show]
      resource :schedule, only: [:show, :update]
      get 'commercials/render_commercial' => 'commercials#render_commercial'
      resources :commercials, only: [:index, :create, :update, :destroy]
      get '/dietary_choices' => 'dietchoices#show', as: 'dietary_list'
      patch '/dietary_choices' => 'dietchoices#update', as: 'dietary_update'
      get '/volunteers_list' => 'volunteers#show'
      get '/volunteers' => 'volunteers#index', as: 'volunteers_info'
      patch '/volunteers' => 'volunteers#update', as: 'volunteers_update'

      resources :registrations, except: [:create, :new] do
        member do
          patch :toggle_attendance

        end
      end

      # Singletons
      resource :splashpage
      resource :venue do
        resources :rooms, except: [:show]
      end
      resource :registration_period
      resource :program do
        resource :cfp
        resources :tracks
        resources :event_types
        resources :difficulty_levels
        resources :events do
          member do
            post :comment
            patch :accept
            patch :confirm
            patch :cancel
            patch :reject
            patch :unconfirm
            patch :restart
            get :vote
          end
          resource :speaker, only: [:edit, :update]
        end
      end

      resources :tickets
      resources :sponsors, except: [:show]
      resources :lodgings, except: [:show]
      resources :targets, except: [:show]
      resources :campaigns, except: [:show]
      resources :emails, only: [:show, :update, :index]
      resources :roles, except: [ :new, :create ] do
        member do
          post :toggle_user
        end
      end

      resources :sponsorship_levels, except: [:show] do
        member do
          patch :up
          patch :down
        end
      end

      resources :questions do
        collection do
          patch :update_conference
        end
      end
    end
  end

  resources :conference, only: [:index, :show] do
    resource :program, except: :destroy do
      resources :proposal, except: :destroy do
        get 'commercials/render_commercial' => 'commercials#render_commercial'
        resources :commercials, only: [:create, :update, :destroy]
        member do
          patch '/withdraw' => 'proposal#withdraw'
          patch '/confirm' => 'proposal#confirm'
          patch '/restart' => 'proposal#restart'
          get '/vote' => 'proposal#vote'
        end
      end
    end

    # TODO: change conference_registrations to singular resource
    resource :conference_registrations, path: 'register' do
      collection do
        get :confirmcheck
        patch :confirmupdate
      end
    end
    resources :tickets, only: [:index]
    resources :ticket_purchases, only: [:create, :destroy]
    resource :subscriptions, only: [:create, :destroy]

    member do
      get :schedule
      get :new_proposals
      get :completeschedule
      get :subnationalschedule
      get :eventlists
      get :attendeelist
    end

  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :conferences, only: [ :index, :show ] do
        resources :rooms, only: :index
        resources :tracks, only: :index
        resources :speakers, only: :index
        resources :events, only: :index
      end
      resources :rooms, only: :index
      resources :tracks, only: :index
      resources :speakers, only: :index
      resources :events, only: :index
    end
  end

  get '/admin' => redirect('/admin/conference')

  root to: 'conference#index', via: [:get, :options]
end

app/models/lodging.rb
class Lodging < ActiveRecord::Base
  belongs_to :conference

  validates :name, presence: true

  has_attached_file :photo,
                    styles: { thumb: '100x100>', large: '300x300>' }

  validates_attachment_content_type :photo,
                                    content_type: [/jpg/, /jpeg/, /png/, /gif/],
                                    size: { in: 0..500.kilobytes }
end

app/controllers/admin/lodgings_controller.rb
module Admin
  class LodgingsController < Admin::BaseController
    load_and_authorize_resource :conference, find_by: :short_title
    load_and_authorize_resource :lodging, through: :conference

    def index
    end

    def new
      @lodging = @conference.lodgings.new
    end

    def create
      @lodging = @conference.lodgings.new(lodging_params)
      if @lodging.save
        redirect_to admin_conference_lodgings_path(conference_id: @conference.short_title),
                    notice: 'Lodging successfully created.'
      else
        flash[:error] = "Creating Lodging failed: #{@lodging.errors.full_messages.join('. ')}."
        render :new
      end
    end

    def edit; end

    def update
      if @lodging.update_attributes(lodging_params)
        redirect_to admin_conference_lodgings_path(conference_id: @conference.short_title),
                    notice: 'Lodging successfully updated.'
      else
        flash[:error] = "Update Lodging failed: #{@lodging.errors.full_messages.join('. ')}."
        render :edit
      end
    end

    def destroy
      if @lodging.destroy
        redirect_to admin_conference_lodgings_path(conference_id: @conference.short_title),
                    notice: 'Lodging successfully deleted.'
      else
        redirect_to admin_conference_lodgings_path(conference_id: @conference.short_title),
                    error: 'Deleting lodging failed.' \
                    "#{@lodging.errors.full_messages.join('. ')}."
      end
    end

    private

    def lodging_params
      params.require(:lodging).permit(:name, :description, :photo, :website_link, :conference_id)
    end
  end
end

app/views/admin/lodgings/_form.html.haml
.row
  .col-md-12
    .page-header
      %h1
        - if @lodging.new_record?
          New
        Lodging
        = @lodging.name
.row
  .col-md-8
    = semantic_form_for(@lodging, :url => (@lodging.new_record? ? admin_conference_lodgings_path : admin_conference_lodging_path(@conference.short_title, @lodging))) do |f|
      = f.input :name
      = f.input :website_link
      = f.input :description, input_html: { rows: 5, cols: 20, data: { provide: 'markdown-editable' } }, hint: markdown_hint
      - unless @lodging.photo.blank?
        = image_tag @lodging.photo(:thumb)
      = f.input :photo
      %p.text-right
        = f.action :submit, as: :button, button_html: { class: 'btn btn-primary' }

app/views/admin/lodgings/index.html.haml
.row
  .col-md-12
    .page-header
      %h1 Lodgings
      %p.text-muted
        Recommended some Hotels, Motels, Hostels or Campsites around your venue

- @conference.lodgings.each_slice(3) do |slice|
  .row
    - slice.each do |lodging|
      .col-md-4
        .thumbnail
          - if lodging.photo.blank?
            %p.text-center
              %i.fa.fa-home.fa-5x
          - else
            -if lodging.website_link.present?
              = link_to(lodging.website_link, class: 'thumbnail') do
                = image_tag lodging.photo(:thumb), class: 'img-responsive img-lodging'
            - else
              = image_tag lodging.photo(:thumb), class: 'img-responsive img-lodging'
          .caption
            %h3.text-center
              = lodging.name
            -if lodging.description.present?
              = markdown(lodging.description)
          .actions.text-right
            = link_to 'Edit', edit_admin_conference_lodging_path(@conference.short_title, lodging), class: 'btn btn-primary'
            = link_to 'Delete', admin_conference_lodging_path(@conference.short_title, lodging),
                method: :delete, class: 'btn btn-danger', data: { confirm: "Do you really want to delete the lodging #{lodging.name}?" }


.row
  .col-md-12.text-right
    = link_to 'Add Lodging', new_admin_conference_lodging_path(@conference.short_title), class: 'btn btn-primary'