config/routes.rb
Osem::Application.routes.draw do

  if CONFIG['authentication']['ichain']['enabled']
    devise_for :users, controllers: { registrations: :registrations }
  else
    devise_for :users,
               controllers: {
                   registrations: :registrations, confirmations: :confirmations,
                   omniauth_callbacks: 'users/omniauth_callbacks' },
               path: 'accounts'
  end

  # Use letter_opener_web to open mails in browser (e.g. necessary for Vagrant)
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :users, except: [:new, :index, :create, :destroy]

  namespace :admin do
    resources :users
    resources :people
    resources :comments, only: [:index]
    resources :conference do
      resource :contact, except: [:index, :new, :create, :show, :destroy]
      resources :photos, except: [:show]
      resource :schedule, only: [:show, :update]
      get 'commercials/render_commercial' => 'commercials#render_commercial'
      resources :commercials, only: [:index, :create, :update, :destroy]
      get '/dietary_choices' => 'dietchoices#show', as: 'dietary_list'
      patch '/dietary_choices' => 'dietchoices#update', as: 'dietary_update'
      get '/volunteers_list' => 'volunteers#show'
      get '/volunteers' => 'volunteers#index', as: 'volunteers_info'
      patch '/volunteers' => 'volunteers#update', as: 'volunteers_update'

      resources :registrations, except: [:create, :new] do
        member do
          patch :toggle_attendance

        end
      end

      # Singletons
      resource :splashpage
      resource :venue do
        resources :rooms, except: [:show]
      end
      resource :registration_period
      resource :program do
        resource :cfp
        resources :tracks
        resources :event_types
        resources :difficulty_levels
        resources :events do
          member do
            post :comment
            patch :accept
            patch :confirm
            patch :cancel
            patch :reject
            patch :unconfirm
            patch :restart
            get :vote
          end
          resource :speaker, only: [:edit, :update]
        end
      end

      resources :tickets
      resources :sponsors, except: [:show]
      resources :lodgings, except: [:show]
      resources :targets, except: [:show]
      resources :campaigns, except: [:show]
      resources :emails, only: [:show, :update, :index]
      resources :roles, except: [ :new, :create ] do
        member do
          post :toggle_user
        end
      end

      resources :sponsorship_levels, except: [:show] do
        member do
          patch :up
          patch :down
        end
      end

      resources :questions do
        collection do
          patch :update_conference
        end
      end
    end
  end

  resources :conference, only: [:index, :show] do
    resource :program, except: :destroy do
      resources :proposal, except: :destroy do
        get 'commercials/render_commercial' => 'commercials#render_commercial'
        resources :commercials, only: [:create, :update, :destroy]
        member do
          patch '/withdraw' => 'proposal#withdraw'
          patch '/confirm' => 'proposal#confirm'
          patch '/restart' => 'proposal#restart'
          get '/vote' => 'proposal#vote'
        end
      end
    end

    # TODO: change conference_registrations to singular resource
    resource :conference_registrations, path: 'register' do
      collection do
        get :confirmcheck
        patch :confirmupdate
      end
    end
    resources :tickets, only: [:index]
    resources :ticket_purchases, only: [:create, :destroy]
    resource :subscriptions, only: [:create, :destroy]

    member do
      get :schedule
      get :new_proposals
      get :completeschedule
      get :subnationalschedule
      get :eventlists
      get :attendeelist
    end

  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :conferences, only: [ :index, :show ] do
        resources :rooms, only: :index
        resources :tracks, only: :index
        resources :speakers, only: :index
        resources :events, only: :index
      end
      resources :rooms, only: :index
      resources :tracks, only: :index
      resources :speakers, only: :index
      resources :events, only: :index
    end
  end

  get '/admin' => redirect('/admin/conference')

  root to: 'conference#index', via: [:get, :options]
end

app/models/difficulty_level.rb
class DifficultyLevel < ActiveRecord::Base
  belongs_to :program
  has_many :events, dependent: :nullify

  validates :title, presence: true
end

app/controllers/admin/difficulty_levels_controller.rb
module Admin
  class DifficultyLevelsController < Admin::BaseController
    load_and_authorize_resource :conference, find_by: :short_title
    load_and_authorize_resource :program, through: :conference, singleton: true
    load_and_authorize_resource through: :program

    def index
#       authorize! :index, DifficultyLevel.new(program_id: @program.id)
    end

    def edit; end

    def new
      @difficulty_level = @conference.program.difficulty_levels.new
    end

    def create
      @difficulty_level = @conference.program.difficulty_levels.new(difficulty_level_params)
      if @difficulty_level.save
        redirect_to admin_conference_program_difficulty_levels_path(conference_id: @conference.short_title),
                    notice: 'Difficulty level successfully created.'
      else
        flash[:error] = "Creating difficulty level failed: #{@difficulty_level.errors.full_messages.join('. ')}."
        render :new
      end
    end

    def update
      if @difficulty_level.update_attributes(difficulty_level_params)
        redirect_to admin_conference_program_difficulty_levels_path(conference_id: @conference.short_title),
                    notice: 'Difficulty level successfully updated.'
      else
        flash[:error] = "Update difficulty level failed: #{@difficulty_level.errors.full_messages.join('. ')}."
        render :edit
      end
    end

    def destroy
      if @difficulty_level.destroy
        redirect_to admin_conference_program_difficulty_levels_path(conference_id: @conference.short_title),
                    notice: 'Difficulty level successfully deleted.'
      else
        redirect_to admin_conference_program_difficulty_levels_path(conference_id: @conference.short_title),
                    error: 'Deleting difficulty level type failed! '\
                    "#{@difficulty_level.errors.full_messages.join('. ')}."
      end
    end

    private

    def difficulty_level_params
      params.require(:difficulty_level).permit(:title, :description, :color, :conference_id)
    end
  end
end

app/views/admin/difficulty_levels/_form.html.haml
.row
  .col-md-12
    .page-header
      %h1
        - if @difficulty_level.new_record?
          New
        Difficulty Level
        = @difficulty_level.title
.row
  .col-md-8
    = semantic_form_for(@difficulty_level, :url => (@difficulty_level.new_record? ? admin_conference_program_difficulty_levels_path : admin_conference_program_difficulty_level_path(@conference.short_title, @difficulty_level))) do |f|
      = f.input :title, :required => true
      = f.input :description, :input_html => {:rows => 3, :class => "span6"}
      = f.input :color, :input_html => {:size => 6, :type => "color"}
      %p.text-right
        = f.action :submit, as: :button, button_html: { class: 'btn btn-primary' }

app/views/admin/difficulty_levels/index.html.haml
.row
  .col-md-12
    .page-header
      %h1 Difficulty Levels
      %p.text-muted
        Classify your conference.program.events by difficulty
.row
  .col-md-12
    %table.table.table-hover#difficulty_levels
      %thead
        %th Title
        %th Description
        %th Color
        %th Actions
      %tbody
        - @conference.program.difficulty_levels.each do |difficulty_level|
          %tr
            %td
              = difficulty_level.title
            %td
              = difficulty_level.description
            %td
              %span.label{style: "background-color: #{difficulty_level.color};"}
                = difficulty_level.color
            %td
              .btn-group{role: "group"}
                = link_to 'Edit', edit_admin_conference_program_difficulty_level_path(@conference.short_title, difficulty_level.id),
                method: :get, class: 'btn btn-primary'
                = link_to 'Delete', admin_conference_program_difficulty_level_path(@conference.short_title, difficulty_level.id),
                method: :delete, class: 'btn btn-danger',
                data: { confirm: "Do you really want to delete #{difficulty_level.title}? Attention: This difficulty level will be removed from all Events that have it set" }
.row
  .col-md-12.text-right
    = link_to 'Add Difficulty Level', new_admin_conference_program_difficulty_level_path(@conference.short_title), class: 'btn btn-primary'