config/routes.rb
Osem::Application.routes.draw do

  if CONFIG['authentication']['ichain']['enabled']
    devise_for :users, controllers: { registrations: :registrations }
  else
    devise_for :users,
               controllers: {
                   registrations: :registrations, confirmations: :confirmations,
                   omniauth_callbacks: 'users/omniauth_callbacks' },
               path: 'accounts'
  end

  # Use letter_opener_web to open mails in browser (e.g. necessary for Vagrant)
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :users, except: [:new, :index, :create, :destroy]

  namespace :admin do
    resources :users
    resources :people
    resources :comments, only: [:index]
    resources :conference do
      resource :contact, except: [:index, :new, :create, :show, :destroy]
      resources :photos, except: [:show]
      resource :schedule, only: [:show, :update]
      get 'commercials/render_commercial' => 'commercials#render_commercial'
      resources :commercials, only: [:index, :create, :update, :destroy]
      get '/dietary_choices' => 'dietchoices#show', as: 'dietary_list'
      patch '/dietary_choices' => 'dietchoices#update', as: 'dietary_update'
      get '/volunteers_list' => 'volunteers#show'
      get '/volunteers' => 'volunteers#index', as: 'volunteers_info'
      patch '/volunteers' => 'volunteers#update', as: 'volunteers_update'

      resources :registrations, except: [:create, :new] do
        member do
          patch :toggle_attendance

        end
      end

      # Singletons
      resource :splashpage
      resource :venue do
        resources :rooms, except: [:show]
      end
      resource :registration_period
      resource :program do
        resource :cfp
        resources :tracks
        resources :event_types
        resources :difficulty_levels
        resources :events do
          member do
            post :comment
            patch :accept
            patch :confirm
            patch :cancel
            patch :reject
            patch :unconfirm
            patch :restart
            get :vote
          end
          resource :speaker, only: [:edit, :update]
        end
      end

      resources :tickets
      resources :sponsors, except: [:show]
      resources :lodgings, except: [:show]
      resources :targets, except: [:show]
      resources :campaigns, except: [:show]
      resources :emails, only: [:show, :update, :index]
      resources :roles, except: [ :new, :create ] do
        member do
          post :toggle_user
        end
      end

      resources :sponsorship_levels, except: [:show] do
        member do
          patch :up
          patch :down
        end
      end

      resources :questions do
        collection do
          patch :update_conference
        end
      end
    end
  end

  resources :conference, only: [:index, :show] do
    resource :program, except: :destroy do
      resources :proposal, except: :destroy do
        get 'commercials/render_commercial' => 'commercials#render_commercial'
        resources :commercials, only: [:create, :update, :destroy]
        member do
          patch '/withdraw' => 'proposal#withdraw'
          patch '/confirm' => 'proposal#confirm'
          patch '/restart' => 'proposal#restart'
          get '/vote' => 'proposal#vote'
        end
      end
    end

    # TODO: change conference_registrations to singular resource
    resource :conference_registrations, path: 'register' do
      collection do
        get :confirmcheck
        patch :confirmupdate
      end
    end
    resources :tickets, only: [:index]
    resources :ticket_purchases, only: [:create, :destroy]
    resource :subscriptions, only: [:create, :destroy]

    member do
      get :schedule
      get :new_proposals
      get :completeschedule
      get :subnationalschedule
      get :eventlists
      get :attendeelist
    end

  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :conferences, only: [ :index, :show ] do
        resources :rooms, only: :index
        resources :tracks, only: :index
        resources :speakers, only: :index
        resources :events, only: :index
      end
      resources :rooms, only: :index
      resources :tracks, only: :index
      resources :speakers, only: :index
      resources :events, only: :index
    end
  end

  get '/admin' => redirect('/admin/conference')

  root to: 'conference#index', via: [:get, :options]
end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :program
  has_many :events, dependent: :nullify do
    def new_proposals
      where(state: :new)
    end

    def confirmed
      where(state: :confirmed)
    end
  end

  before_create :generate_guid
  validates :name, presence: true

  validates :name, presence: true

  private

  def generate_guid
    guid = SecureRandom.urlsafe_base64
#     begin
#       guid = SecureRandom.urlsafe_base64
#     end while Person.where(:guid => guid).exists?
    self.guid = guid
  end
end

app/controllers/admin/tracks_controller.rb
module Admin
  class TracksController < Admin::BaseController
    load_and_authorize_resource :conference, find_by: :short_title
    load_and_authorize_resource :program, through: :conference, singleton: true
    load_and_authorize_resource through: :program

    def index; end

    def show
      respond_to do |format|
        format.html { render }
        format.json { render json: @conference.tracks.to_json }
      end
    end

    def new
      @track = @program.tracks.new
    end

    def create
      @track = @program.tracks.new(track_params)
      if @track.save
        redirect_to admin_conference_program_tracks_path(conference_id: @conference.short_title),
                    notice: 'Track successfully created.'
      else
        flash[:error] = "Creating Track failed: #{@track.errors.full_messages.join('. ')}."
        render :new
      end
    end

    def edit; end

    def update
      if @track.update_attributes(track_params)
        redirect_to admin_conference_program_tracks_path(conference_id: @conference.short_title),
                    notice: 'Track successfully updated.'
      else
        flash[:error] = "Track update failed: #{@track.errors.full_messages.join('. ')}."
        render :edit
      end
    end

    def destroy
      if @track.destroy
        redirect_to admin_conference_program_tracks_path(conference_id: @conference.short_title),
                    notice: 'Track successfully deleted.'
      else
        redirect_to admin_conference_program_tracks_path(conference_id: @conference.short_title),
                    error: "Track couldn't be deleted. #{@track.errors.full_messages.join('. ')}."
      end
    end

    private

    def track_params
      params.require(:track).permit(:name, :description, :color)
    end
  end
end

app/controllers/api/v1/tracks_controller.rb
module Api
  module V1
    class TracksController < Api::BaseController
      load_resource :conference, find_by: :short_title
      respond_to :json

      def index
        tracks = @conference ? @conference.program.tracks : Track.all

        respond_with tracks
      end
    end
  end
end

app/views/admin/tracks/_form.html.haml
.row
  .col-md-12
    .page-header
      %h1
        -if @track.new_record?
          New
        = @track.name
        Track
.row
  .col-md-12
    = semantic_form_for(@track, :url => (@track.new_record? ? admin_conference_program_tracks_path : admin_conference_program_track_path(@conference.short_title, @track))) do |f|
      = f.input :name
      = f.input :color, :input_html => {:size => 6, :type => "color"}, :required=> true
      = f.input :description, :input_html => {:rows => 2, data: { provide: "markdown-editable" } }, hint: markdown_hint
      = f.action :submit, as: :button, button_html: { class: 'btn btn-primary' }

app/views/admin/tracks/index.html.haml
.row
  .col-md-12
    .page-header
      %h1 Tracks
      %p.text-muted
        Categorize events in your conference
.row
  .col-md-12
    %table.table.table-hover#tracks
      %thead
        %th Name
        %th Description
        %th Color
        %th Actions
      %tbody
        - @tracks.each do |track|
          %tr
            %td
              = link_to(admin_conference_program_track_path(@conference.short_title, track)) do
                = track.name
            %td
              %p
                = truncate(track.description)
            %td
              %span.label{style: "background-color: #{track.color};"}
                = track.color
            %td
              .btn-group{role: "group"}
                = link_to 'Edit', edit_admin_conference_program_track_path(@conference.short_title, track.id),
                method: :get, class: 'btn btn-primary'
                = link_to 'Delete', admin_conference_program_track_path(@conference.short_title, track.id),
                method: :delete, class: 'btn btn-danger',
                data: { confirm: "Do you really want to delete #{track.name}? Attention: This track will be removed from all Events that have it set" }
.row
  .col-md-12.text-right
    = link_to 'New Track', new_admin_conference_program_track_path(@conference.short_title), class: 'btn btn-success'

app/views/admin/tracks/show.html.haml
.row
  .col-md-12
    .page-header
      %h1
        = @track.name
        Track
      %p.text-muted
        Events in this track
.row
  .col-md-12
    %table.table.table-hover.datatable
      %thead
        %th Title
        %th Type
        %th Submitter
        %th State
        %th Time
      %tbody
        - @track.events.each_with_index do |event|
          %tr
            %td
              =link_to event.title, admin_conference_program_event_path(@conference.short_title, event)
            %td
              = event.event_type.title
            %td
              =link_to event.submitter.name, admin_user_path(event.submitter)
            %td
              = event.state
            %td
              = event.start_time